# Jekyll configuration for Open SDG platform

# primary settings:
baseurl: "/sdg-in-staging-site" # change here!
remote_data_prefix: "https://StabsstelleNachhaltigkeit.github.io/sdg-in-staging-data"

# URL for the "Edit Data" and "Edit Metadata" button on indicators.
data_edit_url: http://prose.io/#StabsstelleNachhaltigkeit/sdg-in-staging-data/edit/develop/data/indicator_[id].csv
metadata_edit_url: http://prose.io/#StabsstelleNachhaltigkeit/sdg-in-staging-data/edit/develop/meta/[id].md

# Text zu Handlungsfelder 
# fields to change: title, vision, leitsatz, hf-goals
frontpage_handlungsfelder:  
  - title: Wirtschaft
    vision: |
      Ingolstadt wirtschaftet in 2045 nachhaltig: Die Wirtschaft schützt den Planeten 
      und stärkt das Gemeinwohl. Nicht nur die Lebensqualität ist auf einem Höchststand. Auch sind 
      Ingolstädter/-innen die zufriedensten Bürger/-innen in Deutschland:
      Die Balance zwischen Arbeit und Leben steht in Ingolstadt im Vordergrund.
    leitsatz: |
      Ingolstadt ist ein attraktiver und nachhaltiger Wirtschaftsstandort. Als
      vernetzte und zukunftsorientierte Stadt sichern wir mit technologischem, sozialem
      und gesellschaftlichem Fortschritt den Wohlstand für alle Menschen in Ingolstadt.
      Ökonomie und Ökologie betrachten wir nicht als Widersprüche, sondern als Quelle
      für Synergien.
    hf-goals: "4,5,8,9,10,11,12,13"
    hf-color: '#007ebe'

  - title: Umwelt
    vision: |
      Ingolstadt verbindet Stadt und Natur und gilt als grüne Lunge unter den
      Städten Bayerns. Ingolstadt versorgt sich selbst mit Energie - ist autark und setzt
      Kreislaufwirtschaft um. Die Donau ist sauber und die CO2-Bilanz der Stadt weist
      aus: Ingolstadt ist klimapositiv.
    leitsatz: |
      Ingolstadt lebt und wirtschaftet klima- und ressourcenschützend. Wir
      schaffen Bewusstsein für den Erhalt unserer natürlichen Lebensgrundlagen und sichern diese.
      Mit einer positiven und effektiven Sichtweise auf die Ökologie treten wir mit Natur und Technik 
      in eine neue Beziehung.
    hf-goals: "2,6,7,9,11,12,13,14,15"
    hf-color: '#65b448'

  - title: Leben
    vision: |
      Der Alltag in Ingolstadt ist geprägt von Lebensqualität – und von einer vielfältigen Mobilität mit einem
      breiten und nutzer/-innenfreundlichen Angebot für alle. Gemeinschaftlichkeit und Wohlbefinden sind Kennzeichen der
      nachhaltigen Stadtviertel der kurzen Wege, in denen sich die Generationen treffen. Zukunftskaufhäuser verdienen an
      langlebigen Produkten zur Nutzung statt zum Besitz, weil sie auch Reparatur anbieten. Seltener wird ganz neu Pro-
      duziertes gekauft.
    leitsatz: |
        Wir ermöglichen ein gesundes und sicheres Miteinander im Alltag für die Menschen
        in Ingolstadt. Das urbane Leben läuft im Einklang mit Mobilität und Ökologie.
    hf-goals: "2,3,6,9,10,11,12,13,15,16"
    hf-color: '#f8b715'

  - title: Vielfalt
    vision: |
      Ingolstadt ist weltoffen und leistet ihren Beitrag zur globalen Verantwortung. 
      Verschiedenheit wird in Ingolstadt respektiert und wertgeschätzt. Engagierte 
      Ingolstädter/-innen stärken den Gemeinsinn. Diskriminierungen hingegen – auch
       bei der Entlohnung – gehören schon lange der Vergangenheit an.
    leitsatz: |
      Die Stadt Ingolstadt steht für Vielfalt, Offenheit und Toleranz. Durch unsere 
      vielfältige Gesellschaft fördern wir Kreativität und Produktivität. Wir engagieren
      uns lokal und global für ein gerechtes, gesundes und inklusives Miteinander. Damit
      fördern wir die Glokalisierung
    hf-goals: "1,2,3,4,5,6,10,11,15,16,17"
    hf-color: '#ed6d29'

  - title: Bildung
    vision: |
      Nachhaltigkeit hat Einzug in Bildungs- und Kultureinrichtungen gehalten.
      Der Zugang zur Kultur ist offen, für alle attraktiv und leicht zugänglich. Bildung selbst
      hat eine neue Qualität: Erfahrungslernen, vernetzter Umgang miteinander und Teil-
      habe sind fester Bestandteil von Bildungsangeboten.
    leitsatz: |
        Wir fördern Bildung für alle Menschen in unserer Stadt, auch mit den 
        Mitteln der Kultur und kulturellen Bildung und leisten damit einen wichtigen Beitrag für
        eine nachhaltige Zukunft.
    hf-goals: "4,9,10,11,16"
    hf-color: '#05afda'


email_contacts:
  questions: nachhaltigkeit@ingolstadt.de
  suggestions: nachhaltigkeit@ingolstadt.de
  functional: nachhaltigkeit@ingolstadt.de


# 
# other settings are alphabetically ordered:
analytics:
  ga_prod: ''

collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true
    permalink: /news/:year/:month/:day/:title.html
  indicators:
    output: true
  goals:
    output: true

country: # or place name
  name: Ingolstadt
  adjective: Ingolstadt
  
create_indicators:
  layout: indicator
create_goals:
  previous_next_links: false
  goals: []
create_pages:
  - filename: ''
    folder: /goals
    layout: goals
    title: general.goals
  - filename: ''
    folder: /reporting-status
    layout: reportingstatus
    title: status.reporting_status
  - filename: ''
    folder: /search
    layout: search
    title: search.search

custom_js:
  - /assets/js/custom.js
exclude:
  - vendor
  - scripts
  - remotedata
  - Gemfile
  - Gemfile.lock
  - README
  - README.md
  - LICENSE

footer_language_toggle: none
footer_menu:
  - path: https://StadtIngolstadt.github.io/sdg-data/de/zip/all_indicators.zip
    translation_key: Download
  - path: mailto:nachhaltigkeit@ingolstadt.de
    translation_key: menu.contact_us
  - path: /about/cookies-and-privacy/
    translation_key: menu.cookies
  - path: /guidance
    translation_key: menu.guidance

frontpage_introduction_banner:
 title: my-custom-translations.frontpage-intro-title
 description: my-custom-translations.frontpage-intro-description

frontpage_goals_grid:
  title: my-custom-translations.my-goals-grid-title
  description: my-custom-translations.my-goals-grid-description

frontpage_handlungsfelder_title:
  hf-title: my-custom-translations.my-hf-title
  hf-subtitle: my-custom-translations.my-hf-subtitle

frontpage_cards:
  - title: Nachhaltigkeitsbericht - Stadt Ingolstadt 2021
    href: "https://nachhaltigkeitsagenda-ingolstadt.de/wp-content/uploads/2023/01/221208_BNK_final_web.pdf" 
    thumbnail_src: /BNK_Titelbild.jpg
  - title: Magazin - "Ingolstadt Nachhaltig" - Ausgabe 2022
    href: "https://nachhaltigkeitsagenda-ingolstadt.de/wp-content/uploads/2023/01/IN_Magazin_dpa-CC_FINAL_DIGTAL.pdf"
    thumbnail_src: /IN_Magazin_Titelbild.jpg
  - title: Nachhaltigkeitsfilm - Stadt Ingolstadt
    href: "https://www.youtube.com/watch?v=LnqFFrIGQQQ"
    thumbnail_src: /Logo_Nachhaltigkeitsagenda_96dpi.jpg
  - title: Video Rückblick - Visionen 2045 Ingolstadt
    href: "https://www.youtube.com/watch?v=VDQF-RdU0nc"
    thumbnail_src: /Logo_Nachhaltigkeitsagenda_96dpi.jpg

   

goal_image_base: https://open-sdg.org/sdg-translations/assets/img/goals
graph_color_set: accessible
header_language_toggle: dropdown

languages:
  - de

menu:
  - path: /goals
    translation_key: general.goals
  - path: /reporting-status
    translation_key: menu.reporting_status
  - path: /about
    translation_key: menu.about
  - path: /faq
    translation_key: menu.faq
  # - path:
  #   translation_key: 

menu_top:
  - path: /leichte-sprache
    translation_key: menu.plain_german
  # - path:
  #   translation_key: 

metadata_tabs:
  - scope: national
    title: Metadaten
    description: indicator.national_metadata_blurb

plugins:
  - jekyll-remote-theme
  - jekyll-open-sdg-plugins

remote_theme: open-sdg/open-sdg@2.1.0

title: general.site_title
url: ""
environment: staging
